### ISSUE TITLE
does not save new autodrive file format

### ISSUE THREAD

**Issue by Kobra299** [raupach/AutoDrive_RouteManager#7]
this no longer works as it did with the new version of autodrive the save feature does not work

**Comment by raupach** [comment]
I'm going to check it out.

**Comment by raupach** [comment]
fixed.

**Comment by Kobra299** [comment]
where can I download the new file so that it can be fixed on my system as well

**Comment by raupach** [comment]
Have a look at: https://github.com/Stephan-S/FS19_AutoDrive/tree/master/AutoDrive%20Course%20Editor
